# Generated by Django 5.0.6 on 2024-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0002_alter_message_options_alter_message_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_published',)},
        ),
    ]
