# Generated by Django 5.0.6 on 2024-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0007_rename_message_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': [('can_edit_message', 'user can edit message'), ('can_delete_message', 'user can delete message')]},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='date_published',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
